/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WidgetPreviewRouteImport } from './routes/widget-preview'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as StatesRouteImport } from './routes/states'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SessionExpiredRouteImport } from './routes/session-expired'
import { Route as RolePreviewRouteImport } from './routes/role-preview'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MembersRouteImport } from './routes/members'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as ChannelsRouteImport } from './routes/channels'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SettingsAiRouteImport } from './routes/settings.ai'
import { Route as OnboardingWorkspaceRouteImport } from './routes/onboarding.workspace'
import { Route as OnboardingTeamRouteImport } from './routes/onboarding.team'
import { Route as OnboardingProfileRouteImport } from './routes/onboarding.profile'
import { Route as OnboardingDoneRouteImport } from './routes/onboarding.done'
import { Route as OnboardingChannelRouteImport } from './routes/onboarding.channel'
import { Route as OnboardingAiRouteImport } from './routes/onboarding.ai'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as InboxConversationIdRouteImport } from './routes/inbox.$conversationId'
import { Route as DevPillGalleryRouteImport } from './routes/dev.pill-gallery'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers.$customerId'
import { Route as ChatBusinessIdRouteImport } from './routes/chat.$businessId'
import { Route as ChannelsChannelIdRouteImport } from './routes/channels.$channelId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminUsageRouteImport } from './routes/admin.usage'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminProviderHealthRouteImport } from './routes/admin.provider-health'
import { Route as AdminFeatureFlagsRouteImport } from './routes/admin.feature-flags'
import { Route as AdminBusinessesRouteImport } from './routes/admin.businesses'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminBusinessesIndexRouteImport } from './routes/admin.businesses.index'
import { Route as AdminBusinessesBusinessIdRouteImport } from './routes/admin.businesses.$businessId'

const WidgetPreviewRoute = WidgetPreviewRouteImport.update({
  id: '/widget-preview',
  path: '/widget-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const StatesRoute = StatesRouteImport.update({
  id: '/states',
  path: '/states',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionExpiredRoute = SessionExpiredRouteImport.update({
  id: '/session-expired',
  path: '/session-expired',
  getParentRoute: () => rootRouteImport,
} as any)
const RolePreviewRoute = RolePreviewRouteImport.update({
  id: '/role-preview',
  path: '/role-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRoute = ChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SettingsAiRoute = SettingsAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => SettingsRoute,
} as any)
const OnboardingWorkspaceRoute = OnboardingWorkspaceRouteImport.update({
  id: '/onboarding/workspace',
  path: '/onboarding/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingTeamRoute = OnboardingTeamRouteImport.update({
  id: '/onboarding/team',
  path: '/onboarding/team',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingProfileRoute = OnboardingProfileRouteImport.update({
  id: '/onboarding/profile',
  path: '/onboarding/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingDoneRoute = OnboardingDoneRouteImport.update({
  id: '/onboarding/done',
  path: '/onboarding/done',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingChannelRoute = OnboardingChannelRouteImport.update({
  id: '/onboarding/channel',
  path: '/onboarding/channel',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingAiRoute = OnboardingAiRouteImport.update({
  id: '/onboarding/ai',
  path: '/onboarding/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxConversationIdRoute = InboxConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => InboxRoute,
} as any)
const DevPillGalleryRoute = DevPillGalleryRouteImport.update({
  id: '/dev/pill-gallery',
  path: '/dev/pill-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/$customerId',
  path: '/$customerId',
  getParentRoute: () => CustomersRoute,
} as any)
const ChatBusinessIdRoute = ChatBusinessIdRouteImport.update({
  id: '/chat/$businessId',
  path: '/chat/$businessId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsChannelIdRoute = ChannelsChannelIdRouteImport.update({
  id: '/$channelId',
  path: '/$channelId',
  getParentRoute: () => ChannelsRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsageRoute = AdminUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProviderHealthRoute = AdminProviderHealthRouteImport.update({
  id: '/provider-health',
  path: '/provider-health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeatureFlagsRoute = AdminFeatureFlagsRouteImport.update({
  id: '/feature-flags',
  path: '/feature-flags',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBusinessesRoute = AdminBusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBusinessesIndexRoute = AdminBusinessesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminBusinessesRoute,
} as any)
const AdminBusinessesBusinessIdRoute =
  AdminBusinessesBusinessIdRouteImport.update({
    id: '/$businessId',
    path: '/$businessId',
    getParentRoute: () => AdminBusinessesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/admin': typeof AdminRouteWithChildren
  '/audit': typeof AuditRoute
  '/channels': typeof ChannelsRouteWithChildren
  '/customers': typeof CustomersRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/inbox': typeof InboxRouteWithChildren
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/role-preview': typeof RolePreviewRoute
  '/session-expired': typeof SessionExpiredRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signup': typeof SignupRoute
  '/states': typeof StatesRoute
  '/studio': typeof StudioRoute
  '/verify-email': typeof VerifyEmailRoute
  '/widget-preview': typeof WidgetPreviewRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/businesses': typeof AdminBusinessesRouteWithChildren
  '/admin/feature-flags': typeof AdminFeatureFlagsRoute
  '/admin/provider-health': typeof AdminProviderHealthRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/usage': typeof AdminUsageRoute
  '/admin/users': typeof AdminUsersRoute
  '/channels/$channelId': typeof ChannelsChannelIdRoute
  '/chat/$businessId': typeof ChatBusinessIdRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/dev/pill-gallery': typeof DevPillGalleryRoute
  '/inbox/$conversationId': typeof InboxConversationIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/onboarding/ai': typeof OnboardingAiRoute
  '/onboarding/channel': typeof OnboardingChannelRoute
  '/onboarding/done': typeof OnboardingDoneRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/onboarding/team': typeof OnboardingTeamRoute
  '/onboarding/workspace': typeof OnboardingWorkspaceRoute
  '/settings/ai': typeof SettingsAiRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/businesses/$businessId': typeof AdminBusinessesBusinessIdRoute
  '/admin/businesses/': typeof AdminBusinessesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/audit': typeof AuditRoute
  '/channels': typeof ChannelsRouteWithChildren
  '/customers': typeof CustomersRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/inbox': typeof InboxRouteWithChildren
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/role-preview': typeof RolePreviewRoute
  '/session-expired': typeof SessionExpiredRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signup': typeof SignupRoute
  '/states': typeof StatesRoute
  '/studio': typeof StudioRoute
  '/verify-email': typeof VerifyEmailRoute
  '/widget-preview': typeof WidgetPreviewRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/feature-flags': typeof AdminFeatureFlagsRoute
  '/admin/provider-health': typeof AdminProviderHealthRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/usage': typeof AdminUsageRoute
  '/admin/users': typeof AdminUsersRoute
  '/channels/$channelId': typeof ChannelsChannelIdRoute
  '/chat/$businessId': typeof ChatBusinessIdRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/dev/pill-gallery': typeof DevPillGalleryRoute
  '/inbox/$conversationId': typeof InboxConversationIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/onboarding/ai': typeof OnboardingAiRoute
  '/onboarding/channel': typeof OnboardingChannelRoute
  '/onboarding/done': typeof OnboardingDoneRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/onboarding/team': typeof OnboardingTeamRoute
  '/onboarding/workspace': typeof OnboardingWorkspaceRoute
  '/settings/ai': typeof SettingsAiRoute
  '/admin': typeof AdminIndexRoute
  '/admin/businesses/$businessId': typeof AdminBusinessesBusinessIdRoute
  '/admin/businesses': typeof AdminBusinessesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/admin': typeof AdminRouteWithChildren
  '/audit': typeof AuditRoute
  '/channels': typeof ChannelsRouteWithChildren
  '/customers': typeof CustomersRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/inbox': typeof InboxRouteWithChildren
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/role-preview': typeof RolePreviewRoute
  '/session-expired': typeof SessionExpiredRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signup': typeof SignupRoute
  '/states': typeof StatesRoute
  '/studio': typeof StudioRoute
  '/verify-email': typeof VerifyEmailRoute
  '/widget-preview': typeof WidgetPreviewRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/businesses': typeof AdminBusinessesRouteWithChildren
  '/admin/feature-flags': typeof AdminFeatureFlagsRoute
  '/admin/provider-health': typeof AdminProviderHealthRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/usage': typeof AdminUsageRoute
  '/admin/users': typeof AdminUsersRoute
  '/channels/$channelId': typeof ChannelsChannelIdRoute
  '/chat/$businessId': typeof ChatBusinessIdRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/dev/pill-gallery': typeof DevPillGalleryRoute
  '/inbox/$conversationId': typeof InboxConversationIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/onboarding/ai': typeof OnboardingAiRoute
  '/onboarding/channel': typeof OnboardingChannelRoute
  '/onboarding/done': typeof OnboardingDoneRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/onboarding/team': typeof OnboardingTeamRoute
  '/onboarding/workspace': typeof OnboardingWorkspaceRoute
  '/settings/ai': typeof SettingsAiRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/businesses/$businessId': typeof AdminBusinessesBusinessIdRoute
  '/admin/businesses/': typeof AdminBusinessesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/admin'
    | '/audit'
    | '/channels'
    | '/customers'
    | '/forgot-password'
    | '/inbox'
    | '/knowledge'
    | '/login'
    | '/members'
    | '/notifications'
    | '/profile'
    | '/role-preview'
    | '/session-expired'
    | '/settings'
    | '/signup'
    | '/states'
    | '/studio'
    | '/verify-email'
    | '/widget-preview'
    | '/admin/audit'
    | '/admin/businesses'
    | '/admin/feature-flags'
    | '/admin/provider-health'
    | '/admin/support'
    | '/admin/usage'
    | '/admin/users'
    | '/channels/$channelId'
    | '/chat/$businessId'
    | '/customers/$customerId'
    | '/dev/pill-gallery'
    | '/inbox/$conversationId'
    | '/invite/$token'
    | '/onboarding/ai'
    | '/onboarding/channel'
    | '/onboarding/done'
    | '/onboarding/profile'
    | '/onboarding/team'
    | '/onboarding/workspace'
    | '/settings/ai'
    | '/admin/'
    | '/admin/businesses/$businessId'
    | '/admin/businesses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-denied'
    | '/audit'
    | '/channels'
    | '/customers'
    | '/forgot-password'
    | '/inbox'
    | '/knowledge'
    | '/login'
    | '/members'
    | '/notifications'
    | '/profile'
    | '/role-preview'
    | '/session-expired'
    | '/settings'
    | '/signup'
    | '/states'
    | '/studio'
    | '/verify-email'
    | '/widget-preview'
    | '/admin/audit'
    | '/admin/feature-flags'
    | '/admin/provider-health'
    | '/admin/support'
    | '/admin/usage'
    | '/admin/users'
    | '/channels/$channelId'
    | '/chat/$businessId'
    | '/customers/$customerId'
    | '/dev/pill-gallery'
    | '/inbox/$conversationId'
    | '/invite/$token'
    | '/onboarding/ai'
    | '/onboarding/channel'
    | '/onboarding/done'
    | '/onboarding/profile'
    | '/onboarding/team'
    | '/onboarding/workspace'
    | '/settings/ai'
    | '/admin'
    | '/admin/businesses/$businessId'
    | '/admin/businesses'
  id:
    | '__root__'
    | '/'
    | '/access-denied'
    | '/admin'
    | '/audit'
    | '/channels'
    | '/customers'
    | '/forgot-password'
    | '/inbox'
    | '/knowledge'
    | '/login'
    | '/members'
    | '/notifications'
    | '/profile'
    | '/role-preview'
    | '/session-expired'
    | '/settings'
    | '/signup'
    | '/states'
    | '/studio'
    | '/verify-email'
    | '/widget-preview'
    | '/admin/audit'
    | '/admin/businesses'
    | '/admin/feature-flags'
    | '/admin/provider-health'
    | '/admin/support'
    | '/admin/usage'
    | '/admin/users'
    | '/channels/$channelId'
    | '/chat/$businessId'
    | '/customers/$customerId'
    | '/dev/pill-gallery'
    | '/inbox/$conversationId'
    | '/invite/$token'
    | '/onboarding/ai'
    | '/onboarding/channel'
    | '/onboarding/done'
    | '/onboarding/profile'
    | '/onboarding/team'
    | '/onboarding/workspace'
    | '/settings/ai'
    | '/admin/'
    | '/admin/businesses/$businessId'
    | '/admin/businesses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessDeniedRoute: typeof AccessDeniedRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuditRoute: typeof AuditRoute
  ChannelsRoute: typeof ChannelsRouteWithChildren
  CustomersRoute: typeof CustomersRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InboxRoute: typeof InboxRouteWithChildren
  KnowledgeRoute: typeof KnowledgeRoute
  LoginRoute: typeof LoginRoute
  MembersRoute: typeof MembersRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  RolePreviewRoute: typeof RolePreviewRoute
  SessionExpiredRoute: typeof SessionExpiredRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SignupRoute: typeof SignupRoute
  StatesRoute: typeof StatesRoute
  StudioRoute: typeof StudioRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  WidgetPreviewRoute: typeof WidgetPreviewRoute
  ChatBusinessIdRoute: typeof ChatBusinessIdRoute
  DevPillGalleryRoute: typeof DevPillGalleryRoute
  InviteTokenRoute: typeof InviteTokenRoute
  OnboardingAiRoute: typeof OnboardingAiRoute
  OnboardingChannelRoute: typeof OnboardingChannelRoute
  OnboardingDoneRoute: typeof OnboardingDoneRoute
  OnboardingProfileRoute: typeof OnboardingProfileRoute
  OnboardingTeamRoute: typeof OnboardingTeamRoute
  OnboardingWorkspaceRoute: typeof OnboardingWorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/widget-preview': {
      id: '/widget-preview'
      path: '/widget-preview'
      fullPath: '/widget-preview'
      preLoaderRoute: typeof WidgetPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/states': {
      id: '/states'
      path: '/states'
      fullPath: '/states'
      preLoaderRoute: typeof StatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session-expired': {
      id: '/session-expired'
      path: '/session-expired'
      fullPath: '/session-expired'
      preLoaderRoute: typeof SessionExpiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role-preview': {
      id: '/role-preview'
      path: '/role-preview'
      fullPath: '/role-preview'
      preLoaderRoute: typeof RolePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/settings/ai': {
      id: '/settings/ai'
      path: '/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof SettingsAiRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/onboarding/workspace': {
      id: '/onboarding/workspace'
      path: '/onboarding/workspace'
      fullPath: '/onboarding/workspace'
      preLoaderRoute: typeof OnboardingWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/team': {
      id: '/onboarding/team'
      path: '/onboarding/team'
      fullPath: '/onboarding/team'
      preLoaderRoute: typeof OnboardingTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/profile': {
      id: '/onboarding/profile'
      path: '/onboarding/profile'
      fullPath: '/onboarding/profile'
      preLoaderRoute: typeof OnboardingProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/done': {
      id: '/onboarding/done'
      path: '/onboarding/done'
      fullPath: '/onboarding/done'
      preLoaderRoute: typeof OnboardingDoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/channel': {
      id: '/onboarding/channel'
      path: '/onboarding/channel'
      fullPath: '/onboarding/channel'
      preLoaderRoute: typeof OnboardingChannelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/ai': {
      id: '/onboarding/ai'
      path: '/onboarding/ai'
      fullPath: '/onboarding/ai'
      preLoaderRoute: typeof OnboardingAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/$conversationId': {
      id: '/inbox/$conversationId'
      path: '/$conversationId'
      fullPath: '/inbox/$conversationId'
      preLoaderRoute: typeof InboxConversationIdRouteImport
      parentRoute: typeof InboxRoute
    }
    '/dev/pill-gallery': {
      id: '/dev/pill-gallery'
      path: '/dev/pill-gallery'
      fullPath: '/dev/pill-gallery'
      preLoaderRoute: typeof DevPillGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$customerId': {
      id: '/customers/$customerId'
      path: '/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/chat/$businessId': {
      id: '/chat/$businessId'
      path: '/chat/$businessId'
      fullPath: '/chat/$businessId'
      preLoaderRoute: typeof ChatBusinessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels/$channelId': {
      id: '/channels/$channelId'
      path: '/$channelId'
      fullPath: '/channels/$channelId'
      preLoaderRoute: typeof ChannelsChannelIdRouteImport
      parentRoute: typeof ChannelsRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usage': {
      id: '/admin/usage'
      path: '/usage'
      fullPath: '/admin/usage'
      preLoaderRoute: typeof AdminUsageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/provider-health': {
      id: '/admin/provider-health'
      path: '/provider-health'
      fullPath: '/admin/provider-health'
      preLoaderRoute: typeof AdminProviderHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feature-flags': {
      id: '/admin/feature-flags'
      path: '/feature-flags'
      fullPath: '/admin/feature-flags'
      preLoaderRoute: typeof AdminFeatureFlagsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/businesses': {
      id: '/admin/businesses'
      path: '/businesses'
      fullPath: '/admin/businesses'
      preLoaderRoute: typeof AdminBusinessesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/businesses/': {
      id: '/admin/businesses/'
      path: '/'
      fullPath: '/admin/businesses/'
      preLoaderRoute: typeof AdminBusinessesIndexRouteImport
      parentRoute: typeof AdminBusinessesRoute
    }
    '/admin/businesses/$businessId': {
      id: '/admin/businesses/$businessId'
      path: '/$businessId'
      fullPath: '/admin/businesses/$businessId'
      preLoaderRoute: typeof AdminBusinessesBusinessIdRouteImport
      parentRoute: typeof AdminBusinessesRoute
    }
  }
}

interface AdminBusinessesRouteChildren {
  AdminBusinessesBusinessIdRoute: typeof AdminBusinessesBusinessIdRoute
  AdminBusinessesIndexRoute: typeof AdminBusinessesIndexRoute
}

const AdminBusinessesRouteChildren: AdminBusinessesRouteChildren = {
  AdminBusinessesBusinessIdRoute: AdminBusinessesBusinessIdRoute,
  AdminBusinessesIndexRoute: AdminBusinessesIndexRoute,
}

const AdminBusinessesRouteWithChildren = AdminBusinessesRoute._addFileChildren(
  AdminBusinessesRouteChildren,
)

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBusinessesRoute: typeof AdminBusinessesRouteWithChildren
  AdminFeatureFlagsRoute: typeof AdminFeatureFlagsRoute
  AdminProviderHealthRoute: typeof AdminProviderHealthRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminUsageRoute: typeof AdminUsageRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminBusinessesRoute: AdminBusinessesRouteWithChildren,
  AdminFeatureFlagsRoute: AdminFeatureFlagsRoute,
  AdminProviderHealthRoute: AdminProviderHealthRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminUsageRoute: AdminUsageRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ChannelsRouteChildren {
  ChannelsChannelIdRoute: typeof ChannelsChannelIdRoute
}

const ChannelsRouteChildren: ChannelsRouteChildren = {
  ChannelsChannelIdRoute: ChannelsChannelIdRoute,
}

const ChannelsRouteWithChildren = ChannelsRoute._addFileChildren(
  ChannelsRouteChildren,
)

interface CustomersRouteChildren {
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersCustomerIdRoute: CustomersCustomerIdRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

interface InboxRouteChildren {
  InboxConversationIdRoute: typeof InboxConversationIdRoute
}

const InboxRouteChildren: InboxRouteChildren = {
  InboxConversationIdRoute: InboxConversationIdRoute,
}

const InboxRouteWithChildren = InboxRoute._addFileChildren(InboxRouteChildren)

interface SettingsRouteChildren {
  SettingsAiRoute: typeof SettingsAiRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAiRoute: SettingsAiRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessDeniedRoute: AccessDeniedRoute,
  AdminRoute: AdminRouteWithChildren,
  AuditRoute: AuditRoute,
  ChannelsRoute: ChannelsRouteWithChildren,
  CustomersRoute: CustomersRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InboxRoute: InboxRouteWithChildren,
  KnowledgeRoute: KnowledgeRoute,
  LoginRoute: LoginRoute,
  MembersRoute: MembersRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  RolePreviewRoute: RolePreviewRoute,
  SessionExpiredRoute: SessionExpiredRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SignupRoute: SignupRoute,
  StatesRoute: StatesRoute,
  StudioRoute: StudioRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  WidgetPreviewRoute: WidgetPreviewRoute,
  ChatBusinessIdRoute: ChatBusinessIdRoute,
  DevPillGalleryRoute: DevPillGalleryRoute,
  InviteTokenRoute: InviteTokenRoute,
  OnboardingAiRoute: OnboardingAiRoute,
  OnboardingChannelRoute: OnboardingChannelRoute,
  OnboardingDoneRoute: OnboardingDoneRoute,
  OnboardingProfileRoute: OnboardingProfileRoute,
  OnboardingTeamRoute: OnboardingTeamRoute,
  OnboardingWorkspaceRoute: OnboardingWorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
